### ISSUE TITLE
Add a note explaining the choice to not use PR approach for GitOps scenario

### ISSUE THREAD

**Issue by rafaeltuelho** [RedHat-Middleware-Workshops/mad-dev-guides-m3#2]
Users may get confused while performing changes using ArgoCD UI instead of sending PRs (GitOps recommended approach).

**Comment by danieloh30** [comment]
We have recently changed the way developers modify the application configuration via the ArgoCD directly due to the performance issue even if this might not be better DevEx. To reduce the provisioning time and increase performance, we clone the original repository to integrate with the ArgoCD (`ApplicationSet`) rather than referring to each user's Gitea repo. That's why the PR based on individual Gitea repo doesn't impact to the application deployment in the ArgoCD.

This is a known issue around DevEX vs. Provision performance. I will trace this to find a better solution in the future release.
